# -*- coding: utf-8 -*-
"""
/***************************************************************************
 palmTreeDetection
                                 A QGIS plugin
 This plugin for Detection Palm tree with YOLO detection model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-18
        copyright            : (C) 2025 by Naufal Najiv Zhorif
        email                : naufalzhorif.2001@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load palmTreeDetection class from file palmTreeDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .palm_tree_detection import palmTreeDetection
    return palmTreeDetection(iface)
