# -*- coding: utf-8 -*-
"""
/***************************************************************************
 palmTreeDetectionDialog
                                 A QGIS plugin
 This plugin for Detection Palm tree with YOLO detection model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Naufal Najiv Zhorif
        email                : naufalzhorif2001@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import gc
import os
import time
import math
from typing import Dict, Any

import torch
import numpy as np
import rasterio
import geopandas as gpd

from shapely.geometry import Point, box
from rasterio.windows import Window, bounds as window_bounds, from_bounds

from sahi import AutoDetectionModel
from sahi.predict import get_sliced_prediction
 
from qgis.core import Qgis, QgsProject, QgsVectorLayer
from qgis.gui import QgsFileWidget
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import QThread, pyqtSignal
from qgis.PyQt.QtWidgets import QApplication
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'palm_tree_detection_dialog_base.ui')
)


RASTERIO_ENV_OPTIONS = {
    "GDAL_CACHEMAX": 512,
    "VSI_CACHE": "TRUE",
}


class DetectionWorker(QThread):
    """
    Worker thread.
    
    This worker processes the raster in blocks to avoid loading the entire
    raster into memory at once. Each block is further sliced by SAHI for
    inference, and detections are filtered to avoid duplicates at block
    boundaries.
    """
    progress = pyqtSignal(str)
    finished = pyqtSignal()
    error = pyqtSignal(str)

    def __init__(self, params: Dict[str, Any]) -> None:
        super().__init__()
        self.params = params

    def _compute_core_box(
        self,
        window: Window,
        overlap_px: float,
        is_first_col: bool,
        is_last_col: bool,
        is_first_row: bool,
        is_last_row: bool,
        raster_transform,
    ):
        """
        Compute the "core" box (in map coordinates) for a window.
        
        The core region is the window's area minus half of the block-to-block
        overlap margin on sides that border another block. This prevents
        double-counting detections in overlap zones.
        """
        core_col_off = window.col_off + (0 if is_first_col else overlap_px // 2)
        core_row_off = window.row_off + (0 if is_first_row else overlap_px // 2)

        core_col_end = window.col_off + window.width - (0 if is_last_col else overlap_px // 2)
        core_row_end = window.row_off + window.height - (0 if is_last_row else overlap_px // 2)

        core_window = Window(
            core_col_off,
            core_row_off,
            max(core_col_end - core_col_off, 0),
            max(core_row_end - core_row_off, 0)
        )

        core_minx, core_miny, core_maxx, core_maxy = window_bounds(
            core_window, raster_transform
        )

        return box(core_minx, core_miny, core_maxx, core_maxy)

    def run(self) -> None:
        """
        Run the palm tree detection pipeline.
        
        Pipeline:
        1. Read boundary shapefile and validate
        2. Open raster and validate
        3. Generate processing grid with overlap
        4. Process each window with SAHI inference
        5. Filter and store detections
        6. Write output and load to QGIS
        """
        try:
            program_start = time.time()

            # Get parameters
            raster = self.params['raster'].dataProvider().dataSourceUri()
            shapefile = self.params['shapefile'].dataProvider().dataSourceUri()
            max_block_size = 4096  # Maximum block size
            slice_size = int(self.params['slice_size'])
            overlap_ratio = float(self.params['overlap'])
            threshold = float(self.params['threshold'])
            detection_model = self.params['model']
            output = self.params['output']

            # Parameter validation
            if slice_size <= 0:
                raise ValueError("Slice size must be greater than 0.")
            if overlap_ratio < 0 or overlap_ratio >= 1:
                raise ValueError("Overlap ratio must be between 0 and 1.")

            # Load shapefile
            self.progress.emit("Reading boundary shapefile...")
            try:
                shp = gpd.read_file(shapefile)
            except Exception:
                try:
                    shp = gpd.read_file(shapefile, engine='pyogrio')
                except Exception:
                    shp = gpd.read_file(shapefile, engine='fiona')

            # Validate shapefile
            if shp.crs is None:
                raise ValueError("Boundary shapefile does not have a CRS.")
            
            
            # Open raster
            self.progress.emit("Opening raster...")
            with rasterio.Env(**RASTERIO_ENV_OPTIONS):
                with rasterio.open(raster, 'r') as src:
                    raster_crs = src.crs
                    raster_width = src.width
                    raster_height = src.height
                    raster_transform = src.transform
                    raster_bands = src.count

                    if raster_crs is None:
                        raise ValueError("Raster does not have a CRS.")
                    if raster_bands != 3:
                        raise ValueError("Raster must have 3 bands (RGB). Found: " + str(raster_bands) + " bands.")

                    self.progress.emit("Raster CRS: " + str(raster_crs))
                    self.progress.emit("Raster size: " + str(raster_width) + " x " + str(raster_height))
                    self.progress.emit("Raster bands: " + str(raster_bands))

                    # Check if shapefile is empty
                    if shp.empty:
                        raise ValueError("No valid geometry found in boundary.")

                    # Merge all boundary features into a single geometry.
                    # (shp.geometry is a GeoSeries; intersects()/covers() on a
                    # GeoSeries return a Series of booleans, not a single
                    # True/False, which breaks the "if ..." checks below.)
                    try:
                        aoi_geometry = shp.geometry.union_all()
                    except AttributeError:
                        aoi_geometry = shp.geometry.unary_union

                    # Get AOI bounds
                    minx, miny, maxx, maxy = aoi_geometry.bounds
                    # Format the bounds without using round() on strings
                    self.progress.emit("AOI bounds: " + 
                                      "{:.3f}, {:.3f}, {:.3f}, {:.3f}".format(minx, miny, maxx, maxy))

                    # Convert AOI bounds to pixel window
                    aoi_window = from_bounds(minx, miny, maxx, maxy, transform=raster_transform)
                    
                    # Full raster window
                    full_window = Window(0, 0, raster_width, raster_height)
                    
                    # Intersect AOI with raster
                    aoi_window = aoi_window.intersection(full_window)
                    
                    if aoi_window.width <= 0 or aoi_window.height <= 0:
                        raise ValueError("Boundary does not overlap the raster.")

                    # Calculate dynamic block size based on AOI dimensions
                    aoi_width = int(aoi_window.width)
                    aoi_height = int(aoi_window.height)
                    
                    # If AOI is smaller than max_block_size, use AOI dimensions
                    if aoi_width < max_block_size and aoi_height < max_block_size:
                        # AOI fits in a single block
                        block_size = max(aoi_width, aoi_height)
                        # Ensure block_size is at least slice_size
                        block_size = max(block_size, slice_size)
                        # Cap at max_block_size
                        block_size = min(block_size, max_block_size)
                        
                        self.progress.emit("using block size: " + str(block_size) + "px")
                    else:
                        # Use max block size for large AOIs
                        block_size = max_block_size
                        self.progress.emit("using block size: " + str(block_size) + "px")

                    # Generate processing grid
                    self.progress.emit("Generating processing grid...")
                    
                    block_overlap_pixels = int(block_size * overlap_ratio)
                    overlap_px = block_overlap_pixels
                    step = block_size - block_overlap_pixels
                    
                    if step <= 0:
                        raise ValueError("Overlap ratio is too high for block size.")

                    start_col = int(math.floor(aoi_window.col_off))
                    start_row = int(math.floor(aoi_window.row_off))
                    end_col = int(math.ceil(aoi_window.col_off + aoi_window.width))
                    end_row = int(math.ceil(aoi_window.row_off + aoi_window.height))

                    windows = []
                    row = start_row
                    
                    while row < end_row:
                        col = start_col
                        while col < end_col:
                            width = min(block_size, end_col - col)
                            height = min(block_size, end_row - row)
                            
                            if width > 0 and height > 0:
                                window = Window(col, row, width, height)
                                
                                # Get window bounds
                                w_minx, w_miny, w_maxx, w_maxy = window_bounds(
                                    window, raster_transform
                                )
                                window_polygon = box(w_minx, w_miny, w_maxx, w_maxy)
                                
                                # Only process windows that intersect AOI
                                if window_polygon.intersects(aoi_geometry):
                                    is_first_col = col <= start_col
                                    is_last_col = (col + width) >= end_col
                                    is_first_row = row <= start_row
                                    is_last_row = (row + height) >= end_row
                                    
                                    windows.append((
                                        window,
                                        is_first_col,
                                        is_last_col,
                                        is_first_row,
                                        is_last_row,
                                    ))
                            
                            col += step
                        row += step

                    total_windows = len(windows)
                    
                    if total_windows == 0:
                        raise ValueError("No processing window intersects the boundary.")

                    self.progress.emit("Total processing windows: " + str(total_windows))
                    self.progress.emit("Block size: " + str(block_size) + "px | Slice size: " + str(slice_size) + "px | Overlap: " + str(overlap_ratio))

                    # Result storage
                    all_points = []
                    
                    detection_start = time.time()
                    total_detected = 0

                    # Process each window
                    for index, window_data in enumerate(windows, start=1):
                        window, is_first_col, is_last_col, is_first_row, is_last_row = window_data
                        
                        try:
                            self.progress.emit("Processing " + str(index) + "/" + str(total_windows))
                            
                            # Read current block
                            image = src.read(window=window)
                            
                            if image.size == 0:
                                continue
                            
                            # Convert band order from bands height width to height width bands
                            image = np.moveaxis(image, 0, -1)
                            
                            # Make contiguous
                            image = np.ascontiguousarray(image)
                            
                            # Handle band count
                            image = image[:, :, :3]
                            
                            # Get window transform
                            window_transform = src.window_transform(window)
                            
                            # Compute core region for this block
                            core_box = self._compute_core_box(
                                window,
                                overlap_px,
                                is_first_col,
                                is_last_col,
                                is_first_row,
                                is_last_row,
                                raster_transform,
                            )
                            
                            # SAHI inference
                            result = get_sliced_prediction(
                                image,
                                detection_model,
                                slice_height=slice_size,
                                slice_width=slice_size,
                                overlap_height_ratio=overlap_ratio,
                                overlap_width_ratio=overlap_ratio,
                                perform_standard_pred=False,
                                verbose=0
                            )
                            
                            # Process predictions
                            window_count = 0
                            
                            for object_detection in result.object_prediction_list:
                                # Get confidence score
                                score_obj = getattr(object_detection, "score", None)
                                score_value = 1.0
                                
                                if score_obj is not None:
                                    try:
                                        score_value = float(score_obj)
                                    except (TypeError, ValueError):
                                        if hasattr(score_obj, "value"):
                                            score_value = float(score_obj.value)
                                        elif hasattr(score_obj, "score"):
                                            score_value = float(score_obj.score)
                                
                                if score_value < threshold:
                                    continue
                                
                                # Get bounding box
                                bbox = object_detection.bbox
                                center_x = (bbox.minx + bbox.maxx) / 2.0
                                center_y = (bbox.miny + bbox.maxy) / 2.0
                                
                                # Convert local pixel to global map coordinate
                                x_coord, y_coord = rasterio.transform.xy(
                                    window_transform, center_y, center_x
                                )
                                point = Point(x_coord, y_coord)
                                
                                # Core region filter
                                if not core_box.covers(point):
                                    continue
                                
                                # AOI filter
                                if not aoi_geometry.covers(point):
                                    continue
                                
                                
                                # Store result
                                all_points.append(point)
                                window_count += 1
                            
                            total_detected = len(all_points)
                            
                            # Progress update
                            progress_percent = (index / total_windows) * 100.0
                            self.progress.emit(
                                "Window " + str(index) + "/" + str(total_windows) + 
                                " (" + "{:.1f}".format(progress_percent) + "%) | " +
                                "Trees: " + str(total_detected)
                            )
                            
                            # Clean memory
                            del result, image
                            gc.collect()
                            
                            if torch.cuda.is_available():
                                torch.cuda.empty_cache()
                        
                        except Exception as window_error:
                            self.progress.emit("WARNING: Window " + str(index) + " failed: " + str(window_error))
                            continue

                    # Detection complete
                    detection_time = time.time() - detection_start
                    self.progress.emit("Detection completed.")
                    
                    # Create GeoDataFrame
                    self.progress.emit("Creating result layer...")
                    gdf = gpd.GeoDataFrame(geometry=all_points, crs=raster_crs)
                    
                    # Write output as Shapefile
                    self.progress.emit("Writing output...")
                    gdf.to_file(output, driver="ESRI Shapefile")
                    
                    # Load result to QGIS
                    shp_name = os.path.splitext(os.path.basename(output))[0]
                    shp_layer = QgsVectorLayer(output, shp_name, "ogr")
                    
                    if not shp_layer.isValid():
                        raise ValueError("Output layer was created but could not be loaded into QGIS.")
                    
                    QgsProject.instance().addMapLayer(shp_layer)
                    
                    # Final statistics
                    total_runtime = time.time() - program_start
                    detection_minutes = int(detection_time // 60)
                    detection_seconds = int(detection_time % 60)
                    runtime_minutes = int(total_runtime // 60)
                    runtime_seconds = int(total_runtime % 60)
                    
                    self.progress.emit("================================")
                    self.progress.emit("Detection completed successfully.")
                    self.progress.emit("Tree Detected: " + str(len(all_points)))
                    self.progress.emit("Detection Time: " + str(detection_minutes) + " min " + str(detection_seconds) + " sec")
                    self.progress.emit("Total Runtime: " + str(runtime_minutes) + " min " + str(runtime_seconds) + " sec")
                    self.progress.emit("Result saved to: " + output)
                    self.progress.emit("================================")
                    
                    # Clean up
                    del all_points, gdf, shp, aoi_geometry
                    
        except Exception as e:
            self.error.emit(str(e))
        
        finally:
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            self.finished.emit()


class palmTreeDetectionDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(palmTreeDetectionDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        self.outputShp.setStorageMode(QgsFileWidget.SaveFile)
        self.outputShp.setFilter('Shapefiles (*.shp)')
        
        self.runPlugin.clicked.connect(self.run_detection)
        self.detection_model = None
        self.detection_threshold = None
        self.worker = None
        self.is_running = False  # Track if detection is running
        
    def run_detection(self):
        """
        Run the detection process in a separate thread.
        """
        # Check if already running
        if self.is_running:
            self.log_message("Detection is already running...")
            return
        
        # Validate inputs
        if not self.validate_inputs():
            return
        
        self.runPlugin.setEnabled(False)
        self.is_running = True
        
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.log_message("Using device: " + device)
        
        if torch.cuda.is_available():
            try:
                gpu_name = torch.cuda.get_device_name(0)
                self.log_message("GPU: " + gpu_name)
            except Exception:
                pass
        
        threshold = self.inputThreshold.value()
        self.log_message("Confidence threshold: " + str(threshold))
        
        # Load model
        if self.detection_model is None or self.detection_threshold != threshold:
            try:
                self.detection_model = AutoDetectionModel.from_pretrained(
                    model_type='yolov8',
                    model_path=self.inputModel.filePath(),
                    confidence_threshold=threshold,
                    device=device,
                )
                self.detection_threshold = threshold
                iface.messageBar().pushMessage("Info", "Detection model loaded", level=Qgis.Info)
            except Exception as e:
                self.show_error("Failed to load model: " + str(e))
                return
        
        # Prepare parameters
        params = {
            'raster': self.inputRaster.currentLayer(),
            'shapefile': self.inputShapefile.currentLayer(),
            'model': self.detection_model,
            'slice_size': int(self.inputTileSize.text()),
            'overlap': self.inputOverlapRatio.value(),
            'threshold': threshold,
            'output': self.outputShp.filePath()
        }
        
        # Create and start worker
        self.worker = DetectionWorker(params)
        self.worker.progress.connect(self.log_message)
        self.worker.error.connect(self.on_error)
        self.worker.finished.connect(self.on_detection_finished)
        self.worker.start()
    
    def validate_inputs(self):
        """Validate that all required inputs are set."""
        if self.inputRaster.currentLayer() is None:
            self.show_error("Please select an input raster layer.")
            return False
        
        if self.inputShapefile.currentLayer() is None:
            self.show_error("Please select an input boundary layer.")
            return False
        
        if not self.inputModel.filePath():
            self.show_error("Please select a YOLO (ultralytics) model.")
            return False
        
        if not self.outputShp.filePath():
            self.show_error("Please choose an output path.")
            return False
        
        return True
    
    def on_error(self, msg):
        """Handle worker error."""
        self.show_error(msg)
    
    def show_error(self, msg):
        """Show error message and re-enable button."""
        self.runPlugin.setEnabled(True)
        self.is_running = False
        iface.messageBar().pushMessage("Error", msg, level=Qgis.Critical)
        self.cleanup_worker()

    def on_detection_finished(self):
        """Handle worker finished."""
        self.runPlugin.setEnabled(True)
        self.is_running = False
        self.cleanup_worker()
    
    def cleanup_worker(self):
        """Clean up worker resources."""
        if self.worker is not None:
            self.worker.deleteLater()
            self.worker = None
        
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            
    def log_message(self, message):
        """Log message to QGIS message bar."""
        iface.messageBar().pushMessage("Info", message, level=Qgis.Info)
        QApplication.processEvents()
    
    def closeEvent(self, event):
        """Handle dialog close event."""
        if self.is_running:
            # Ask user if they want to stop detection
            reply = QtWidgets.QMessageBox.question(
                self,
                'Detection in Progress',
                'Detection is still running. Do you want to stop it and close?',
                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                QtWidgets.QMessageBox.No
            )
            
            if reply == QtWidgets.QMessageBox.Yes:
                # Stop the worker if running
                if self.worker is not None and self.worker.isRunning():
                    self.worker.terminate()
                    self.worker.wait()
                self.cleanup_worker()
                event.accept()
            else:
                event.ignore()
        else:
            event.accept()